import { Geist, Geist_Mono } from "next/font/google";
// import { Outfit } from "next/font/google";
import { Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Home/Navbar";
import Footer from "@/components/Home/Footer";

const outFit = Rubik({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "USFRANC 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${outFit.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <div>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
